trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'  
jobs:
- job: Build
  displayName: 'Build .NET 8.0 Application'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.x'  # Specify the .NET SDK version you need
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - checkout: self  # Check out the code from the repository

  - script: dotnet restore
    displayName: 'Restore dependencies'

  - script: dotnet build --no-restore --configuration Release
    displayName: 'Build project'

  - script: dotnet test --no-build --verbosity normal
    displayName: 'Run tests'

  - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)/publish
    displayName: 'Publish project'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/publish'
      artifact: 'drop'
    displayName: 'Publish build artifact'
